FROM quay.io/sampandey001/secktor
RUN git clone https://github.com/kushansewmina1234/DARK-SHAN-MD-0.0.1V/root/Maccoder3
WORKDIR /root/Maccoder3/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
